### ISSUE TITLE
Revive the Teamtailor integration

### ISSUE THREAD

**Issue by fenske** [fenske/devskills-app#65]
### User Story
As a user, I want to be able to seamlessly use DevSkills via Teamtailor.

### AC

- [x] Update `/config` to request candidate's GitHub username (mandatory), challenge id list & labels (optional) (30 min)
- [x] Figure out where to get company id from in Teamtailor (URL?) 0m It's in the URL
- [x] Implement flows
  - [x] When `/webhook` received -> update the partner result to send assignment metadata (30 min)
  - [x] Test result updated -> update the partner result's test status (15 min)
  - [x] Tags updates -> update the partner results details. (15 min)
- [x] Test batch update
- [x] Record demo - 15 min

**Comment by fenske** [comment]
### TODO
#### Webhooks
- Company ID mapping between Teamtailor and DevSkills (Teamtailor UUID param)
- candidate ID mapping
- Candidate's GitHub username custom field

#### Partner Result
- status mapping (Teamtailor “sending”, “sent”, “pending”, “completed” or “failed”.)
- assessment object mapping (in Teamtailor it's score and grade)
- candidate ID mapping

**Comment by fenske** [comment]
Partner Result attachments can be used for sharing:

- Repo URL
- Scorecard URL
- Rubric URL

Partner Result details can be used for sharing the tests status and tags

**Comment by fenske** [comment]
### Data Model
#### Easy solution
- Add `teamtailorId` to the org doc.
- Add `teamtailorPartnerResultId` to the assignment doc.

**Comment by fenske** [comment]
### Hooks
- Test result updated -> update the partner result's test status
- Tags updates -> update the partner results details.

**Comment by fenske** [comment]
### Clean-up OR re-structure procedure if needed
- Find all orgs with `teamtailorId`
- Find all assignments with `teamtailorPartnerResultId`

**Comment by fenske** [comment]
## Proposal
### Data model
Each affected doc should have an `integrationsContext` object field which holds integration specific aspect of the corresponding Firestore doc.

E.g.,
`organizations/{uid}`
- `integrationContext`
  - teamtailor
    - company
      - uuid  
  - lever
  - greenhouse

- `organizations/{uid}/assignments/{assignmentId}`
  -  integrationContext
    - teamtailor
      - partnerResult
        - id  
    - lever
    - greenhouse

**Comment by fenske** [comment]
### Task 1
1. Update & release config.
2. Test it with Teamtailor.

**Comment by fenske** [comment]
Blocker: gitHub username is not part of teamtailor's candidate.

**Comment by fenske** [comment]
### Refactoring

- [ ] Same challenge list source
- [ ] Extract updating partner result
- [ ] Remove unnecessary logging
- [ ] User not found handling
- [ ] Break stuff down into methods

**Comment by fenske** [comment]
### Testing
- [ ] Correct repo links
- [ ] Wrong GitHub username error handling
